### ISSUE TITLE
other tablet or smartphone ?

### ISSUE THREAD

**Issue by wilfried18** [gearbench/geardroid-app-installer#2]
I wonder why the script is available for the Nexus 7 and not other tablet or smartphone?

**Comment by danigearbench** [comment]
I initially wrote it for myself, it should be fine on any device but the orbot build used it for lollipop.  I only have Nexus 7 2012 & 2013 to test ;)

**Comment by danigearbench** [comment]
I will also update the scripts to allow installation of CF Autoroot and CWM for those devices

**Comment by wilfried18** [comment]
Thankx
